### ISSUE TITLE
Staging QA: Narrow mode - reset Scroll position when clicking a Tag

### ISSUE THREAD

**Issue by flukeout** [mozilla/network-pulse#801] opened 2017-10-23 17:21 UTC
**Steps to reproduce**

* Open any entry in narrow mode (single column layout)
* Scroll down to its tags and click one
* This will load a tag view
* Result: The page is scrolled down somewhat, sometimes between two entries
* Expectation: The page is scrolled to the top

**Comment by mmmavis** [comment] 2017-11-09 01:08
This only happens when you click on the `tag` that you originally came from and I think this is the expected behaviour. 

e.g., 

1. visit https://www.mozillapulse.org/tags/mozfest
2. click on "Sharing Resources for Making Webgames" project card ![screenshot-2017-11-8 sharing resources for making webgames - mozilla network pulse](https://user-images.githubusercontent.com/2896608/32583054-831c1182-c4a6-11e7-83a7-48514cddf4bf.jpg)
3. clicking on the "mozfest" tag should bring you back to the "mozfest" tag list with the preserved scroll position (you should see "Sharing Resources for Making Webgames" card in the viewport); whereas clicking on a different tag (for example "gaming") will bring you to the "gaming" tag list with scroll position reset to the top.

Thoughts or suggestions?

**Comment by xmatthewx** [comment] 2017-11-09 14:37
ah, i see the confusion. @mmmavis that's great implementation. and good sleuthing. thanks! this is not a bug. closing.

**Closed by xmatthewx** 2017-11-09 14:37 UTC
Labels: help wanted, QA
