### ISSUE TITLE
Browser console CSP/XHR errors

### ISSUE THREAD

**Issue by alanmoo** [mozilla/network-pulse#704] opened 2017-09-22 18:13 UTC
When opening the production site there's some CSP issues.
When going into the moderation tab there's an "XHR Request Cancelled" error.

**Comment by cadecairos** [comment] 2017-09-26 20:50
@alanmoo where is this moderation tab?

**Comment by mmmavis** [comment] 2017-09-26 21:23
@cadecairos if you have admin rights and are logged in, you can visit `/moderation` directly to get to that page (there should also be a link on nav bar says "moderation").

**Comment by mmmavis** [comment] 2017-09-26 21:26
ummm I see the errors locally and on other pages as well 😢 
<img width="1417" alt="screen shot 2017-09-26 at 2 24 28 pm" src="https://user-images.githubusercontent.com/2896608/30885007-8b4a5b5e-a2c6-11e7-84d8-4d5b37e3cc83.png">

https://github.com/mozilla/network-pulse/blob/master/js/security-headers.js anything we need to update here?

**Comment by cadecairos** [comment] 2017-09-26 21:31
I see this error: 
```
Content Security Policy: The page’s settings blocked the loading of a resource at https://platform.twitter.com/widgets/twitter_cookies.html?namespace=twttr%3Acookies&origin=https%3A%2F%2Fwww.mozillapulse.org (“child-src 'none'”). 
```

kinda crappy that our twitter share seems to be trying to load tracking beacons.

**Comment by cadecairos** [comment] 2017-09-26 21:35
also, if make sure that you check with any content blockers disabled, because they can modify content CSPs.

**Comment by alanmoo** [comment] 2017-09-27 14:04
Even with content blockers off I'm seeing the same issues.

**Comment by cadecairos** [comment] 2017-09-28 15:31
here's the URL being blocked: `https://api.mozillapulse.org/api/pulse/entries/?showCounter=true&moderationstate=Pending&page=1&ordering=-created&page_size=24&format=json`

I'm not sure why yet - maybe CORS?

**Comment by cadecairos** [comment] 2017-09-28 15:53
Actually, nevermind about that last URL.

I think I'm zeroing in on the issue. If you look at your XHR logs while loading the moderation page, you notice that `https://api.mozillapulse.org/api/pulse/userstatus/` is hit twice, and `https://api.mozillapulse.org/api/pulse/entries/moderation-states/?format=json` is hit three times.

I suspect that the cancelled request is to `api/pulse/userstatus`, and we're seeing multiple requests here because of how react is triggering events while loading the page. I haven't looked into the react code, but maybe we need to rework how it's mounting components or which event we trigger XHR requests from.

@mmmavis is far more familiar with this code than I am though, so I leave it to her to confirm this theory

**Comment by alanmoo** [comment] 2017-09-28 16:09
Great, thanks for the exploration. Let's leave this as a bit lower priority since nothing's specifically "broken", but keep it on the sprint for visibility.

**Comment by mmmavis** [comment] 2018-05-02 18:28
Closing. CSP issues have been fixed. I can't seem to reproduce the "XHR Request Cancelled" issues on moderation page. I'll create a new ticket if I encounter it in the future.

**Closed by mmmavis** 2018-05-02 18:28 UTC
Labels: bug :bug:
