### ISSUE TITLE
Implement add issue descriptions to issues tab

### ISSUE THREAD

**Issue by kristinashu** [mozilla/network-pulse#516] opened 2017-05-03 16:25 UTC
Based on design in https://github.com/mozilla/network-pulse/issues/204

This design adds content to what is currently on https://www.mozillapulse.org/issues

Copy is pulled from https://www.mozilla.org/en-US/foundation/issues/ and @alanmoo says he already has the description for each issue in the database, so you don't have to manually paste them in to a route.

Click on the _issue tag_ or the _issue title_ should show the filtered view e.g. https://www.mozillapulse.org/issues/online-privacy-and-security

![desktop - issues landing 2x](https://cloud.githubusercontent.com/assets/1068783/25670535/d8cda172-2fe1-11e7-9ed8-cc99d4ea24c0.png)

**Comment by xmatthewx** [comment] 2017-05-05 18:51
excellent

**Comment by Sudip7** [comment] 2017-05-08 03:39
@kristinashu , is the filtered view is predefined meaning every time it lands on the same page or it's going to be random.

 Also little clarification required for issue tag. I believe when one search issue tag, the result should be same as when Issues tab is clicked.

**Comment by xmatthewx** [comment] 2017-05-08 21:17
hi @Sudip7. When a user taps the Issues item in the main menu, they will see the design above with the 5 issues descriptions. https://www.mozillapulse.org/issues

A user can then either tap one of the 5 issue buttons or the title of the issue description (in pink). These would then load the specific issues. Items load in the order sent by the API. Not random. 

For this engineering task, there will be no change to the view of an individual issue (.../issues/decentralization). Just an up date to the top issues page (.../issues)

Searching for an issue name will still go to the search view. This allows a user to adjust their search. They will see similar projects, but not the exact same list. That is fine. 

Does that answer your questions?

**Comment by Sudip7** [comment] 2017-05-09 03:06
I got some idea. But @xmatthewx @kristinashu , don't you guys think it's going to be duplicate functionality. I mean both the button and new link would basically display the same page. Either we could stick to the current form or move to more descriptive mode and remove the above tags. 

@Pomax @mmmavis any suggestions !!!

**Comment by mmmavis** [comment] 2017-05-09 08:13
@Sudip7 sorry I'm not sure what you meant. Did you mean the **issue button** and the **issue title link** on the `/issues` page will send users to the same issue page (e.g., `/issues/decentralization`) ? If so I think it's fine to have multiple elements leading users to the same destination.

**Comment by Sudip7** [comment] 2017-05-09 23:11
@mmmavis I meant to say that as per the new design suggestions there would be both issue buttons(not tab)  and hyperlinks​(pink text) doing the same thing. So we would end up having 5 issues type buttons on top and 5 hyperlink with brief descriptions in the page body. So i believe it's a kind of duplication. Either we could stick to current page style or migrate to new design where there would be no issues button on page but the hyperlinks.

**Comment by xmatthewx** [comment] 2017-05-10 15:49
@Sudip7 – when a user is viewing `/issues/decentralization` they will only see the issue buttons for navigation to another issue. The descriptions are only visible on `/issues`, and on this view, a new users might be focused on the descriptions and learning about the issues. The link on heading is a duplicate of the button, but it serves the users well.

**Comment by mmmavis** [comment] 2017-05-19 19:47
I need some break from another PR I'm currently working on. Gonna take this one on as my "getaway" from that PR. 😉

**Comment by mmmavis** [comment] 2017-05-19 20:13
@alanmoo I'm thinking if it makes sense to have the `/issues` route on Pulse API return a list of `issue` object?

i.e., 

instead of returning
```js

[
    "Web Literacy",
    "Online Privacy & Security",
    "Digital Inclusion",
    "Decentralization",
    "Open Innovation"
]
```

return 

```js

[
    { 
      name: "Web Literacy",
      description: "..."
    },
    { 
      name: "Online Privacy & Security",
      description: "..."
    },
   ...
]
```

This way we don't have to make 5 API calls just to get all the descriptions we want to display on this page. Thoughts?

**Comment by alanmoo** [comment] 2017-05-19 21:10
Makes sense to me. Is it easy to update the front-end to be able to handle both cases as an interim approach so we don't have to closely coordinate an update to the back-end?

Something like 

`if typeof response[0] === 'string' { new code } else {old code}`?

**Closed** 2017-07-11 22:07 UTC
Labels: front-end
