### ISSUE TITLE
Layout Issues in Safari

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network-pulse#209] opened 2016-09-13 03:21 UTC
A few layout bugs in Safari.
### List view
- [ ] In list views, item cards appear in a single column. Hearts are not in the bottom right corner. 

<img width="1118" alt="screenshot 2016-09-12 23 09 47" src="https://cloud.githubusercontent.com/assets/53411/18460272/133bfa44-793e-11e6-846f-5316021bcba1.png">
### Detail view
- [ ] In the detail view (Safari on the right), the Visit button and Link icon are missing. 

<img width="947" alt="screenshot 2016-09-12 23 11 50" src="https://cloud.githubusercontent.com/assets/53411/18460348/b4cd68fc-793e-11e6-9916-622537b54d39.png">
### Search
- [ ] In all browsers, #search .dismiss has no right margin. Can we change right:0; to right:18px;? 25% bigger would be great too. It's so hard to see.

**Comment by mmmavis** [comment] 2016-09-13 17:39
@xmatthewx I'm unable to reproduce the bug. I tested on Safari v9.1.2 Mac OS X 10.11.6. 

<img width="1022" alt="screen shot 2016-09-13 at 10 37 14 am" src="https://cloud.githubusercontent.com/assets/2896608/18484617/16e97c2e-799e-11e6-94df-38654959b8c7.png">

<img width="605" alt="screen shot 2016-09-13 at 10 38 35 am" src="https://cloud.githubusercontent.com/assets/2896608/18484678/45de65ee-799e-11e6-968c-aad3df82d96e.png">

**Comment by xmatthewx** [comment] 2016-09-13 19:56
I see. Looks like Safari is stuck at version 8.0.5 for OS X 10.10.3.

**Comment by mmmavis** [comment] 2017-01-10 19:56
I probably won't get to this since

1) this only happens on specific version of Safari
2) we are going to launch v2 soon and this is a v1 minor bug

**Comment by mmmavis** [comment] 2017-01-19 18:43
For the reasons above. I'm gonna close this ticket 😉

**Closed by mmmavis** 2017-01-19 18:43 UTC
Labels: bug, QA, v1 (current)
