### ISSUE TITLE
Search does weird zoom effect on mobile

### ISSUE THREAD

**Issue by kristinashu** [mozilla/network-pulse#127] opened 2016-08-08 22:58 UTC
When I click on the search box the screen zooms in and breaks the layout. The layout is broken even after closing search. Clicking on search should not zoom in.

Screen caps of production site before/during/after tapping on search bar
![screen-shot-2016-08-08-at-3 36 44-pm](https://cloud.githubusercontent.com/assets/1068783/17499136/6d424d92-5d80-11e6-96f1-f5e7954400f8.jpg)

**Comment by mmmavis** [comment] 2016-08-09 00:29
I'm unable to reproduce this on iPhone 6s and Nexus 4. 👀 @xmatthewx @acabunoc @cadecairos mind checking?

**Comment by cadecairos** [comment] 2016-08-09 00:40
No problems on my Galaxy S7 (Firefox, Firefox beta, and chrome)

Could this be a screen resolution problem?

**Comment by kristinashu** [comment] 2016-08-09 01:01
Actually, facebook in browser (not the native app) is zooming weird for me too so maybe it's a bigger issue. Happens in FF, Safari and Chrome.

I'm on iPhone SE with iOS 9.3.4

**Comment by kristinashu** [comment] 2016-08-09 16:35
Also happening on Natalie's iPhone 5

**Comment by mmmavis** [comment] 2016-08-09 17:46
I guess this is some sort of default mobile browser enhancement thing. We probably need to enlarge the font size of the input if we want to solve this problem for some devices.

**Comment by xmatthewx** [comment] 2016-08-09 21:35
If I remember correctly, setting the base font-size on body to 16px+ prevents this. Or maybe font-size for the inputs. Didn't we hit something similar in the event app?

**Comment by mmmavis** [comment] 2016-08-09 23:21
> If I remember correctly, setting the base font-size on body to 16px+ prevents this. Or maybe font-size for the inputs. Didn't we hit something similar in the event app?

@xmatthewx yup I think so.

I can set base font size to 16px. Do we want to consider changing font size of project description from 15px to 16px? I realize currently no text in our app is in font size 16px 😁

**Comment by xmatthewx** [comment] 2016-08-10 03:50
Works for me.

**Comment by kristinashu** [comment] 2016-08-18 21:06
It also zooms when I click on the link icon.

**Comment by mmmavis** [comment] 2017-02-24 00:05
Was a bug on v1. Closing.

**Closed by mmmavis** 2017-02-24 00:05 UTC
Labels: dev, QA
