### ISSUE TITLE
No indication that submit process is underway

### ISSUE THREAD

**Issue by secretrobotron** [mozilla/network-pulse#455] opened 2017-04-04 14:10 UTC
When you click "submit", nothing on the page tells you it's working. I clicked a couple of times, and started to debug, and then the page suddenly changed. Might be good to have a spinner, or to grey out the submit button, or something.

**Comment by secretrobotron** [comment] 2017-04-04 14:14
Hahah I just found out that I have added my project 3 times as a result.

**Comment by alanmoo** [comment] 2017-04-04 15:19
Eeek. I deleted the extra copies.

**Comment by secretrobotron** [comment] 2017-04-04 15:20
Hehehe thank you 👍

**Comment by Pomax** [comment] 2017-04-04 15:26
Confirmed - the submit button stays clickable after you submit the form and data transfer is in progress, which makes it look to the user like "nothing is happening" when in fact the browser is pushing bytes to the api server as hard as it can. Especially with a reasonably sized image attached to the form, this can easily take several seconds, which is long enough for the user to conclude things are broken and close the app again (or navigate to some other part) and thus breaking off the entry submission.

@mmmavis @xmatthewx we might need a bit of design to make this "look good" but as immediate fix we can disable the submit button when it gets pressed and change its label to "Submitting..." with an animated ellipsis?

**Comment by alanmoo** [comment] 2017-04-04 15:28
Animated? You're taking this a step fancier than I was imagining.

**Comment by Pomax** [comment] 2017-04-04 15:34
We already have an animated ellipses in network-pulse, used while featured/latest are loading in.

**Comment by secretrobotron** [comment] 2017-04-04 15:40
👍 that's what I was thinking too. As long as it looks like the site responds to the user's actions, and is still "alive". ❤️ for animated "..."s.

**Comment by xmatthewx** [comment] 2017-04-04 15:48
Can we disable the button and make it gray? I'm down with animated dots.

**Comment by Pomax** [comment] 2017-04-04 17:08
I'll do it in two steps, first landing the disabling and then we can embellish in follow-up

**Comment by Pomax** [comment] 2017-04-04 17:26
part 1 is in PR review under https://github.com/mozilla/network-pulse/pull/459 atm

**Comment by mmmavis** [comment] 2017-04-12 21:34
@Pomax 's PR was merged days ago (thanks @Pomax ) I like the way it is now . I think we can close this ticket now? /cc @kristinashu for design input since she's not in this thread already.

### default state

<img width="325" alt="screen shot 2017-04-12 at 2 29 36 pm" src="https://cloud.githubusercontent.com/assets/2896608/24980414/f29ba74e-1f8c-11e7-88cd-35abcf2e8ee4.png">

### submitting entry (submit button is disabled)

<img width="335" alt="screen shot 2017-04-12 at 2 29 09 pm" src="https://cloud.githubusercontent.com/assets/2896608/24980415/f2baa46e-1f8c-11e7-91e4-8378416e813a.png">

**Comment by kristinashu** [comment] 2017-04-12 21:38
That looks great @mmmavis!

**Comment by mmmavis** [comment] 2017-04-12 21:41
Yayyy 🎉

**Closed by mmmavis** 2017-04-12 21:41 UTC
Labels: bug
