### ISSUE TITLE
Display extended profile on Pulse

### ISSUE THREAD

**Issue by alanmoo** [mozilla/network-pulse#923] opened 2018-02-13 18:51 UTC
If a user's "extended profile" is enabled, visiting `/profile/{id}` should show all the details added as part of that extended profile

**Comment by xmatthewx** [comment] 2018-02-13 18:53
Comp by @kristinashu  https://redpen.io/qua34b5932cdb6cf9f

**Comment by xmatthewx** [comment] 2018-02-14 20:05
depends on #916

**Comment by mmmavis** [comment] 2018-06-25 23:06
@xmatthewx do you think we can close this ticket as well? This to me looks like a dupe of https://github.com/mozilla/network-pulse/issues/929 ?

**Closed** 2018-06-26 19:49 UTC
